version: '3'

services: 
    app:
        build:
            context: ./biturl
            dockerfile: Dockerfile
        command: uwsgi uwsgi.ini
        ports:
            - "5000:5000"
        depends_on: 
            - db
            - cache
        networks: 
            - appnetwork
            # - cache_nw
    db:
        image: postgres:latest
        restart: always
        # env_file: ./biturl/.db.env
        environment:
            - POSTGRES_USER=ibrahim
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=my_biturl
        ports:
            - "5432:5432"
        networks:
            - appnetwork
        volumes:
            - ./postgres.conf:/etc/postgres.conf
            - ./postgres-data:/var/lib/postgresql/data
    cache:
        image: "redis:alpine"
        ports: 
            - "6379"
        networks: 
            - appnetwork
    # nginx:
    #     image: nginx:latest
    #     ports:
    #         - "8000:80"
   

networks:
    appnetwork:
        driver: bridge
    # db_nw:
    #     driver: bridge
    # cache_nw:
    #     driver: bridge

# volumes: 
#     - database-data:
    
